import fs from 'fs';
import matter from 'gray-matter';
import Link from 'next/link';
import path from 'path';
import BlurImage from '../components/blur-image';
import Layout from '../components/Layout';
import { getRouteImageMeta } from '../utils/image-api';
import { postFilePaths, POSTS_PATH } from '../utils/mdxUtils';

export default function Index({ posts, imgMeta }) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <BlurImage alt="Gray cat" {...imgMeta['test-image.png']} />
      <BlurImage alt="Butterfly cat" {...imgMeta['butterfly-cat.jpg']} />
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <Link href="/page-2">
        <a>Page 2</a>
      </Link>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/posts/${post.filePath.replace(/\.mdx?$/, '')}`}
              href={`/posts/[slug]`}
            >
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  );
}

export async function getStaticProps() {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
    const { content, data } = matter(source);

    return {
      content,
      data,
      filePath
    };
  });

  const imgMeta = await getRouteImageMeta('', true);

  return { props: { posts, imgMeta } };
}
